"""edited tablenames

Revision ID: 29e1e9a03f4c
Revises: ded7686c806e
Create Date: 2024-04-24 13:17:22.937099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e1e9a03f4c'
down_revision: Union[str, None] = 'ded7686c806e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_country', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_of_country')
    )
    op.create_table('noodles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_noodles', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('recommendation', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(length=150), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('name_of_noodles')
    )
    op.drop_table('Noodles')
    op.drop_table('Country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Country',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Country_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name_of_country', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Country_pkey'),
    sa.UniqueConstraint('name_of_country', name='Country_name_of_country_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Noodles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Noodles_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name_of_noodles', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['Country.id'], name='Noodles_country_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Noodles_pkey'),
    sa.UniqueConstraint('image', name='Noodles_image_key'),
    sa.UniqueConstraint('name_of_noodles', name='Noodles_name_of_noodles_key')
    )
    op.drop_table('noodles')
    op.drop_table('country')
    # ### end Alembic commands ###
