"""edited cascade

Revision ID: a5a281781dfb
Revises: 4edaeed73287
Create Date: 2024-04-25 16:32:36.208762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a281781dfb'
down_revision: Union[str, None] = '4edaeed73287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('noodles_country_id_fkey', 'noodles', type_='foreignkey')
    op.create_foreign_key(None, 'noodles', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'noodles', type_='foreignkey')
    op.create_foreign_key('noodles_country_id_fkey', 'noodles', 'country', ['country_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
