"""added ondelete

Revision ID: ded7686c806e
Revises: 782557848c6c
Create Date: 2024-04-24 12:32:48.292920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded7686c806e'
down_revision: Union[str, None] = '782557848c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Noodles_country_id_fkey', 'Noodles', type_='foreignkey')
    op.create_foreign_key(None, 'Noodles', 'Country', ['country_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Noodles', type_='foreignkey')
    op.create_foreign_key('Noodles_country_id_fkey', 'Noodles', 'Country', ['country_id'], ['id'])
    # ### end Alembic commands ###
